### ISSUE TITLE
Which version of python and CUDA is used ?

### ISSUE THREAD

**Issue by zobeirraisi** [backtime92/CRAFT-Reimplementation#8]

**Comment by backtime92** [comment]
@zobeirraisi python 3.6, CUDA 10.0

**Comment by Flowingsun007** [comment]
python版本无所谓，3.6/3.7都行，关键是cuda和pytorch版本（我是cuda10/cuda10.1 +Ubuntu18.04的环境）

刚开始conda装的torch-0.4.1 ＋cuda9/cuda92/cudatoolkit10都不行，训练时报错：
```
# RuntimeError: cuda runtime error (11) : invalid argument at
# /opt/conda/conda-bld/pytorch_1535493744281/work/aten/src/THC/THCGeneral.cpp:663
```
后来把pytorch版本换了一下就可以正常运行了：
`conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=10.0`
【仅供参考】

**Comment by raghavgurbaxani** [comment]
@Flowingsun007  I am getting the same error 'cuda runtime error'. Can you tell me how you solved it ?
